server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api-gateway/ {
    proxy_pass http://api-gateway:8000/;
    proxy_http_version 1.1;
    proxy_buffering off;
  }

  location /news-service/ {
    proxy_pass http://news-service:8000/;
    proxy_http_version 1.1;
  }
}
